services:
  pg-auth:
    image: postgres:14-alpine3.17
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_AUTH_DB}
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
    ports:
      - "${PORT_FROM}:${PORT_TO}"
    volumes:
      - postgres_volume3:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: ./migration_auth.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-auth

volumes:
  postgres_volume3:
